# Generated by Django 5.2.4 on 2025-07-21 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LigneProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postes', to='Maintenance.ligneproduction')),
                ('operateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poste', to='Maintenance.operateur')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_constructeur', models.CharField(max_length=50, unique=True)),
                ('etat', models.CharField(choices=[('fonctionnel', 'Fonctionnel'), ('en_panne', 'En panne'), ('maintenance', 'Maintenance'), ('hors_service', 'Hors service')], default='fonctionnel', max_length=20)),
                ('date_achat', models.DateField()),
                ('date_derniere_maintenance', models.DateField(blank=True, null=True)),
                ('poste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='Maintenance.poste')),
            ],
        ),
    ]
