# Generated by Django 5.2.4 on 2025-08-05 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotosMachines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_drive_url', models.URLField(verbose_name='Lien Google Drive')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='Maintenance.machine')),
            ],
        ),
    ]
